apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: ubuntu-node
  name: ubuntu-node
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: ubuntu-node
    spec:
      containers:
      - image: ubuntu-node
        name: ubuntu-node
        ports:
        - containerPort: 22
        resources: {}
      restartPolicy: Always
status: {}
